objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cloufi__Backend_Fees__c</fullName>
        <label>Backend Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cloufi__Upfront_Fees__c</fullName>
        <label>Upfront Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cloufi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Account Name)</relationshipLabel>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloufi__Backend_Fees__c</fullName>
        <label>Backend Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cloufi__Business_DBA_Years_In_Business__c</fullName>
        <label>Years In Business</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cloufi__Dropbox_Folder_Path__c</fullName>
        <label>Dropbox Folder Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloufi__Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Funder)</relationshipLabel>
        <relationshipName>Loans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloufi__Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Loan_Term__c</fullName>
        <label>Loan Term</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cloufi__Monthly_Gross_Sale__c</fullName>
        <label>Monthly Gross Sale</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Payback_Amount__c</fullName>
        <label>Payback Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Percentage_Of_Gross__c</fullName>
        <label>Percentage Of Gross</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cloufi__Upfront_Fees__c</fullName>
        <label>Upfront Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Factor_Rate__c</fullName>
        <label>Factor Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UW_Document_Share__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UW Document Share</label>
    <nameField>
        <displayFormat>UW Share {0000}</displayFormat>
        <label>UW Document Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Document Share</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReviseOfferController_Test.cls
@isTest
public class ReviseOfferController_Test {
    public static testMethod void executeReviseOfferController(){
        ReviseOfferController.OfferWrapperClass testwrap;       
        
        Account acc=new Account();
        acc.Name='Test';
        acc.Cloufi__Upfront_Fees__c=5.2;
        acc.Cloufi__Backend_Fees__c=9.6;
        insert acc;
        
        system.assertNotequals(acc.id,null);
        
        List<Cloufi__Offers__c> lstoffertest = new List<Cloufi__Offers__c>();
        List<ReviseOfferController.OfferWrapperClass> lstOfferWrapper=new List<ReviseOfferController.OfferWrapperClass>();
        integer i=0;
        
        Opportunity loan=new Opportunity(Name='Test',
                                         AccountID = acc.ID,
                                         StageName = 'Qualified',
                                         CloseDate = System.today(),
                                         Cloufi__Payback_Amount__c=2000,
                                         Cloufi__Monthly_Gross_Sale__c=3000,
                                         Cloufi__Funder__c=acc.id,Amount =151250,
                                         Cloufi__Loan_Term__c=7,Cloufi__Account__c=acc.Id, Cloufi__Gross_Profit__c = 200, 
                                        Cloufi__Business_DBA_Years_in_Business__c = 2,
                                        Cloufi__Dropbox_Folder_Path__c = 'Test');
        insert loan;
        
        Cloufi__Submission__c ObjSub = new Cloufi__Submission__c(Cloufi__Opportunity__c=loan.id,Cloufi__Lender__c=acc.id,Cloufi__Status__c='Requested');
        insert objSub;
        
        Cloufi__Offers__c off=new Cloufi__Offers__c(Revision_Notes__c = 'Test',Program_Type__c='MCA',Cloufi__Submission__c=objSub.id,Cloufi__Daily_PB_Amount__c=103,Factor_Rate__c=1.42,Cloufi__Percentage_Of_Gross__c=16,Cloufi__Payback_Amount__c=14500,Cloufi__Terms_In_Months__c=8,Cloufi__Opportunity__c=loan.id,Cloufi__Funder__c = acc.id,Cloufi__Offer_Status__c = 'Pending',Cloufi__Funding_Amount__c = 100);
        Cloufi__Offers__c off2=new Cloufi__Offers__c(Revision_Notes__c = 'Test',Program_Type__c='MCA',Cloufi__Submission__c=objSub.id,Cloufi__Daily_PB_Amount__c=103,Factor_Rate__c=1.42,Cloufi__Percentage_Of_Gross__c=16,Cloufi__Payback_Amount__c=14500,Cloufi__Terms_In_Months__c=8,Cloufi__Opportunity__c=loan.id,Cloufi__Funder__c = acc.id,Cloufi__Offer_Status__c = 'Revision',Cloufi__Funding_Amount__c = 100);
        
        Cloufi__UW_Document__c objUW = new Cloufi__UW_Document__c(Cloufi__URL__c='www.sfdc.com',Name='Test',Stip_Name__c='Signed Application',Cloufi__Opportunity__c=loan.Id, Cloufi__Type__c='Bank Statement', Status__c='Pending');
            insert objUW;
            objUW.Cloufi__URL__c = 'www.salesforce.com';
        	update objUW;
        
            UW_Document_Share__c objShare = new UW_Document_Share__c(Account__c=acc.id,Opportunity__c=loan.id,UW_Documents__c=objUW.id);
            insert objShare;
        
        List<Cloufi__Offers__c> lstTemptest=new List<Cloufi__Offers__c>();
        lstTemptest.add(off);
        insert off;
        insert off2;
        lstOfferWrapper.add(new ReviseOfferController.OfferWrapperClass(off2,1));
        
		PageReference myVfPage = Page.ReviseOffer;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('id', off2.Id);
		ReviseOfferController ctrl=new ReviseOfferController();
        ctrl.getFields();
        ctrl.submissionId = objSub.id;
        ctrl.getIndex = 1;
        ctrl.SaveOffer();
        ctrl.updateSubmission();
        ctrl.queryRelatedOffer();
    }
}