objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <globalPicklist>Business_Countries</globalPicklist>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Revenue__c</fullName>
        <label>Average Monthly Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>$0 - $4,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000 - $9,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$10,000 - $24,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25,000 - $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 - $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CloufiServicing__Submission_Country__c</fullName>
        <label>Submission Country</label>
        <picklist>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Puerto Rico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cloufi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Account Name)</relationshipLabel>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloufi__Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Funder)</relationshipLabel>
        <relationshipName>Loans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloufi__Payback_Amount__c</fullName>
        <label>Payback Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Percentage_Of_Gross__c</fullName>
        <label>Percentage Of Gross</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <globalPicklist>Business_Countries</globalPicklist>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Factor_Rate__c</fullName>
        <label>Factor Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Owner_1_Email__c</fullName>
        <label>Owner 1 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UW_Document_Share__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UW Document Share</label>
    <nameField>
        <displayFormat>UW Share {0000}</displayFormat>
        <label>UW Document Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Document Share</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityofferController_Test.cls
/*****************************************************************
* Author: Techila Global Services Pvt Ltd. (Aditya Mukkawar)
* Class Name: OpportunityofferController_Test
* Created Date: 28-September-2018
* Description:  Test class for OpportunityofferController
*******************************************************************/
/*Author  			| Date       | Description
 Neha				| 26-Jan-2019| Increase test class coverage
**/
@isTest
public class OpportunityofferController_Test {
	public static testMethod void testOpportunityOffer(){
        //Insert Account
        Account objAcc= new Account(Name='Test Acc',country__c='Canada');
        insert objAcc;
        
        Cloufi__Product__c program = new Cloufi__Product__c();
        program.Cloufi__Account__c = objAcc.Id;
        program.Average_Monthly_Revenue__c = 1000;
        insert program;
        
        //Insert Contact
        Contact objCon = new Contact(AccountId=objAcc.id,LastName='Test Contact',Email='test@gmail.com',Contract__c=true);
        insert objCon;
        
        // Insert Opportunity
        Opportunity objOpp = new Opportunity();
        objOpp.Name = 'Test Opportunity';
        objOpp.CloseDate = system.today();
        objOpp.StageName = 'Closed Won';
        objOpp.Owner_1_Email__c ='test@gmail.com';
        objOpp.AccountId = objAcc.id;
        objOpp.Cloufi__Funder__c= objAcc.id;
        objOpp.CloufiServicing__Submission_Country__c = 'Canada';
        insert objOpp;
        
        List<String> otherStipIds = new List<String>();
        List<String> stipIds = new List<String>();
         //Insert UW document
        Cloufi__UW_Document__c objUWDocument = new Cloufi__UW_Document__c(Status__c='Completed',Sent_for_Contract__c=true,Cloufi__URL__c='www.salesforce.com',Cloufi__Type__c='Stip',Cloufi__Opportunity__c=objOpp.id,stip_Name__c='Test',Name = 'Test UW Docu');
        insert objUWDocument ; 
        
        //Insert UW_Document_Share__c
        UW_Document_Share__c objUWDOC = new UW_Document_Share__c(UW_Documents__c = objUWDocument.id, Opportunity__c = objOpp.id);
        insert objUWDOC;
        
        Cloufi__UW_Document__c objUWDocument1 = new Cloufi__UW_Document__c(Status__c='Completed',Sent_for_Contract__c=true,Cloufi__URL__c='www.salesforce.com',Cloufi__Type__c='Stip',Cloufi__Opportunity__c=objOpp.id,stip_Name__c='Test',Name = 'Test UW Docu');
        insert objUWDocument1 ;
        stipIds.add(objUWDocument.id);
        otherStipIds.add(objUWDocument1.id);
        // Insert Offers
        List<Cloufi__Offers__c> lstOffers = new List<Cloufi__Offers__c>();
        Cloufi__Offers__c objOffer = new Cloufi__Offers__c(Cloufi__Offer_Status__c='New',Cloufi__Opportunity__c = objOpp.Id,Cloufi__Terms_In_Months__c=10,Cloufi__Funding_Amount__c=1000,Cloufi__Payback_Amount__c=1000,Factor_Rate__c=1.2,Cloufi__Daily_PB_Amount__c=100,Cloufi__Percentage_Of_Gross__c=10);
        insert objOffer;
        lstOffers.add(objOffer);
        Test.startTest();
            OpportunityofferController objCtrl = new OpportunityofferController();
            OpportunityofferController.fetchOffer(objOpp.id);
            OpportunityofferController.fetchUser();
        	OpportunityofferController.initNewOffer();
            OpportunityofferController.saveOffer(lstOffers);
            OpportunityofferController.cancelOffer(lstOffers);
            OpportunityofferController.getselectOptions(objOffer,'Cloufi__Offer_Status__c');
        	OpportunityofferController.getOtherUWDocumentList(objOpp.id);
            objOpp.StageName = 'Approved';
            Update objOpp;
        	OpportunityofferController.isOppInApprovedStage(objOpp.id);
        	OpportunityofferController.checkSubmissionCountry(objOpp.id);
        	OpportunityofferController.getCompletedUWDocumentList(objOpp.id);
        	OpportunityofferController.requestContract(stipIds, objOpp.id,otherStipIds);
        	OpportunityofferController.isOfferChosen(objOpp.id);
        	OpportunityofferController.isReqDocsAvailable(objOpp.id);
        	OpportunityofferController.getCurrentOpp(objOpp.id);
        	OpportunityofferController.checkForSignedApp(objOpp.id);
        	OpportunityofferController.getProgramDetails(objAcc.Id);
        	Cloufi__Offers__c objOffer1 = new Cloufi__Offers__c(Cloufi__Offer_Status__c='New',Cloufi__Opportunity__c = objOpp.Id,Cloufi__Terms_In_Months__c=10,Cloufi__Funding_Amount__c=1000,Cloufi__Payback_Amount__c=1000,Factor_Rate__c=1.2,Cloufi__Daily_PB_Amount__c=100,Cloufi__Percentage_Of_Gross__c=10);
        	OpportunityofferController.saveNewOfferController(objOffer1,objOpp.id,program.Id);
        Test.stopTest();
        
    }
}