objects/Adobe_Templates__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Adobe Templates</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Are_you_in_Bankruptcy_Consumer_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Are you in Bankruptcy/Consumer Proposal?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Revenue__c</fullName>
        <label>Average Monthly Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>$0 - $4,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000 - $9,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$10,000 - $24,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25,000 - $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 - $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cloufi__Amount_Requested__c</fullName>
        <label>Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Business_DBA_Name__c</fullName>
        <label>Business DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_within_2_4_weeks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interested within 2-4 weeks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Funding__c</fullName>
        <label>Purpose of Funding</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_in_Business__c</fullName>
        <label>Time in Business</label>
        <picklist>
            <picklistValues>
                <fullName>0-3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 months – 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-5 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5-10 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10+ Years</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SendApplicationController_Test.cls
@isTest
public class SendApplicationController_Test {
    
    public static testMethod void testApplicationSend(){
        Lead objLead = new Lead(AnnualRevenue=1562,Fax ='sdvasd',Description='Desc',Email='test@gmail.com',FirstName='name',Website ='www.w3schools.com',Industry = 'Agriculture',MobilePhone = '45455',Phone='6546546',Title='Title',LastName='Name',Company='Company',Status='Open - Not Contacted',NumberOfEmployees = 52,Rating ='Hot',Average_Monthly_Revenue__c='$5,000 - $9,999',Time_in_Business__c='4 months – 1 year',Are_you_in_Bankruptcy_Consumer_Proposal__c=false,Cloufi__Amount_Requested__c=123,Purpose_of_Funding__c='Test',Interested_within_2_4_weeks__c=true);
        insert ObjLead;
        
        Cloufi__Application__c objApplication = new Cloufi__Application__c(Cloufi__First_Name__c='First Name',Cloufi__Last_Name__c='Last Name',Cloufi__Business_Legal_Name__c ='Legal Name',Cloufi__Business_DBA_Name__c='DBA Name',Cloufi__Lead__c=objLead.id);
        insert objApplication;
        
        Adobe_Templates__c objAdobeTemp = new Adobe_Templates__c(name='Adobe Template Id');
        insert objAdobeTemp;
        
        Test.startTest();           
            ApexPages.StandardController sc = new ApexPages.StandardController(objLead);
            apexpages.currentpage().getparameters().put('id',objLead.id);
            SendApplicationController objController = new SendApplicationController(sc);
            objController.adobePDF = true;
            objController.sendAppLink = true;
            objController.sendPDF = false;
            objController.SendApplication();
        
            
        Test.stopTest();
    }
    
    public static testMethod void testSendPDF(){
        Lead objLead = new Lead(AnnualRevenue=1562,Fax ='sdvasd',Description='Desc',Email='test@gmail.com',FirstName='name',Website ='www.w3schools.com',Industry = 'Agriculture',MobilePhone = '45455',Phone='6546546',Title='Title',LastName='Name',Company='Company',Status='Open - Not Contacted',NumberOfEmployees = 52,Rating ='Hot',Average_Monthly_Revenue__c='$5,000 - $9,999',Time_in_Business__c='4 months – 1 year',Are_you_in_Bankruptcy_Consumer_Proposal__c=false,Cloufi__Amount_Requested__c=123,Purpose_of_Funding__c='Test',Interested_within_2_4_weeks__c=true);
        insert ObjLead;
        
        Cloufi__Application__c objApplication = new Cloufi__Application__c(Cloufi__First_Name__c='First Name',Cloufi__Last_Name__c='Last Name',Cloufi__Business_Legal_Name__c ='Legal Name',Cloufi__Business_DBA_Name__c='DBA Name',Cloufi__Lead__c=objLead.id);
        insert objApplication;
        
         Adobe_Templates__c objAdobeTemp = new Adobe_Templates__c(name='Adobe Template Id');
        insert objAdobeTemp;
        
        Test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objLead);
            apexpages.currentpage().getparameters().put('id',objLead.id);
            SendApplicationController objController = new SendApplicationController(sc);
            objController.adobePDF = true;
            objController.objApp = objApplication;
            objController.sendAppLink = false;
            objController.sendPDF = true;
            objController.sendPDFAttach();
        
        Test.stopTest();
    }
    
    public static testMethod void testSendAllAndPDF(){
        Lead objLead = new Lead(AnnualRevenue=1562,Fax ='sdvasd',Description='Desc',Email='test@gmail.com',FirstName='name',Website ='www.w3schools.com',Industry = 'Agriculture',MobilePhone = '45455',Phone='6546546',Title='Title',LastName='Name',Company='Company',Status='Open - Not Contacted',NumberOfEmployees = 52,Rating ='Hot',Average_Monthly_Revenue__c='$5,000 - $9,999',Time_in_Business__c='4 months – 1 year',Are_you_in_Bankruptcy_Consumer_Proposal__c=false,Cloufi__Amount_Requested__c=123,Purpose_of_Funding__c='Test',Interested_within_2_4_weeks__c=true);
        insert ObjLead;
        
        Cloufi__Application__c objApplication = new Cloufi__Application__c(Cloufi__First_Name__c='First Name',Cloufi__Last_Name__c='Last Name',Cloufi__Business_Legal_Name__c ='Legal Name',Cloufi__Business_DBA_Name__c='DBA Name',Cloufi__Lead__c=objLead.id);
        insert objApplication;
        
         Adobe_Templates__c objAdobeTemp = new Adobe_Templates__c(name='Adobe Template Id');
        insert objAdobeTemp;
        
        Test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objLead);
            apexpages.currentpage().getparameters().put('id',objLead.id);
            SendApplicationController objController = new SendApplicationController(sc);
            objController.adobePDF = true;
            objController.sendAppLink = true;
            objController.sendPDF = true;
            objController.SendApplication();
            //objController.sendEmail();
            //objController.sendPDFAttach();
            
        Test.stopTest();
    }
    
    public static testMethod void testWithoutApp(){
        Lead objLead = new Lead(AnnualRevenue=1562,Fax ='sdvasd',Description='Desc',Email='test@gmail.com',FirstName='name',Website ='www.w3schools.com',Industry = 'Agriculture',MobilePhone = '45455',Phone='6546546',Title='Title',LastName='Name',Company='Company',Status='Open - Not Contacted',NumberOfEmployees = 52,Rating ='Hot',Average_Monthly_Revenue__c='$5,000 - $9,999',Time_in_Business__c='4 months – 1 year',Are_you_in_Bankruptcy_Consumer_Proposal__c=false,Cloufi__Amount_Requested__c=123,Purpose_of_Funding__c='Test',Interested_within_2_4_weeks__c=true);
        insert ObjLead;
        
         Adobe_Templates__c objAdobeTemp = new Adobe_Templates__c(name='Adobe Template Id');
        insert objAdobeTemp;
        
        Test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objLead);
            apexpages.currentpage().getparameters().put('id',objLead.id);
            SendApplicationController objController = new SendApplicationController(sc);
            objController.adobePDF = true;
            objController.sendAppLink = true;
            objController.sendPDF = false;
            objController.SendApplication();
        
            objController = new SendApplicationController(sc);
            objController.sendAppLink = false;
            objController.sendPDF = true;
            objController.sendMobile = true;            
            objController.SendApplication();
            /*objController.sendPhone = true;
            objController.SendApplication();*/
        Test.stopTest();
    }
    
    public static testMethod void testWithoutAppForPDF(){
        Lead objLead = new Lead(AnnualRevenue=1562,Fax ='sdvasd',Description='Desc',Email='test@gmail.com',FirstName='name',Website ='www.w3schools.com',Industry = 'Agriculture',MobilePhone = '45455',Phone='6546546',Title='Title',LastName='Name',Company='Company',Status='Open - Not Contacted',NumberOfEmployees = 52,Rating ='Hot',Average_Monthly_Revenue__c='$5,000 - $9,999',Time_in_Business__c='4 months – 1 year',Are_you_in_Bankruptcy_Consumer_Proposal__c=false,Cloufi__Amount_Requested__c=123,Purpose_of_Funding__c='Test',Interested_within_2_4_weeks__c=true);
        insert ObjLead;
        
         Adobe_Templates__c objAdobeTemp = new Adobe_Templates__c(name='Adobe Template Id');
        insert objAdobeTemp;
        
        Test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objLead);
            apexpages.currentpage().getparameters().put('id',objLead.id);            
            SendApplicationController objController = new SendApplicationController(sc);            
            objController = new SendApplicationController(sc);
            objController.adobePDF = true;
            objController.sendAppLink = false;
            objController.sendPDF = true;
            objController.SendApplication();
        Test.stopTest();
    }
    
    public static testMethod void testWithoutAppAndPDF(){
        Lead objLead = new Lead(AnnualRevenue=1562,Fax ='sdvasd',Description='Desc',Email='test@gmail.com',FirstName='name',Website ='www.w3schools.com',Industry = 'Agriculture',MobilePhone = '45455',Phone='6546546',Title='Title',LastName='Name',Company='Company',Status='Open - Not Contacted',NumberOfEmployees = 52,Rating ='Hot',Average_Monthly_Revenue__c='$5,000 - $9,999',Time_in_Business__c='4 months – 1 year',Are_you_in_Bankruptcy_Consumer_Proposal__c=false,Cloufi__Amount_Requested__c=123,Purpose_of_Funding__c='Test',Interested_within_2_4_weeks__c=true);
        insert ObjLead;
        
         Adobe_Templates__c objAdobeTemp = new Adobe_Templates__c(name='Adobe Template Id');
        insert objAdobeTemp;
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new SendApplicationMock());
            ApexPages.StandardController sc = new ApexPages.StandardController(objLead);
            apexpages.currentpage().getparameters().put('id',objLead.id);
            SendApplicationController objController = new SendApplicationController(sc);            
            objController = new SendApplicationController(sc);
            objController.adobePDF = true;
            objController.sendAppLink = true;
            objController.sendPDF = true;
            objController.sendMobile = false;   
            //objController.sendPhone = false;
            objController.SendApplication();            
        Test.stopTest();
    }
}