objects/Cancelled_UW_Document__c.object
<CustomObject>
    <fields>
        <fullName>Stip_Name__c</fullName>
        <label>Stip Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>Cancelled UW Documents</relationshipLabel>
        <relationshipName>Cancelled_UW_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cancelled UW Document</label>
    <nameField>
        <label>Cancelled UW Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cancelled UW Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Submission__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submission</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Revenue__c</fullName>
        <label>Average Monthly Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>$0 - $4,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000 - $9,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$10,000 - $24,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25,000 - $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 - $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cloufi__Business_DBA_Name__c</fullName>
        <label>Business DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Corporate_Name__c</fullName>
        <label>Legal/Corporate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_in_Business__c</fullName>
        <label>Time in Business</label>
        <picklist>
            <picklistValues>
                <fullName>0-3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 months – 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-5 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5-10 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10+ Years</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Revenue__c</fullName>
        <label>Average Monthly Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>$0 - $4,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000 - $9,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$10,000 - $24,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25,000 - $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 - $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bank_statements_Email_to_Sales_Support__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bank statements Email to Sales Support</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled_Dropbox_Folder_Path__c</fullName>
        <label>Cancelled Dropbox Folder Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloufi__Business_DBA_Name__c</fullName>
        <label>Business DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloufi__Dropbox_Folder_Path__c</fullName>
        <label>Dropbox Folder Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cloufi__Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Funder)</relationshipLabel>
        <relationshipName>Loans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_in_Business__c</fullName>
        <label>Time in Business</label>
        <picklist>
            <picklistValues>
                <fullName>10+ Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0-3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 months – 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-5 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5-10 Years</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UW_Document_Share__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UW Document Share</label>
    <nameField>
        <displayFormat>UW Share {0000}</displayFormat>
        <label>UW Document Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Document Share</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UWDocumentsTrigger_Test.cls
/******************************************************************************
Author             | Date           | Description
Aditya Mukkawar    | 16-August-2018 | Update Opportunity stage depending on UW docs
******************************************************************************
 Updates
* Author            | Date            | Description
* Aditya Mukkawar   | 12-October-2018 | Once Signed Application UW Document is Signed make Application completed
* Aditya Mukkawar   | 19-February-2019| Send an email to Sales support address and avoid to send mail to sales support when Signed application is completed
**********************************************************************************/

@isTest
public class UWDocumentsTrigger_Test {
  public static testMethod void executeSignedApp(){
        Cancelled_UW_Document__c objCancelUWDOc = new Cancelled_UW_Document__c(Name = 'Test', URL__c = 'https://www.webopedia.com/TERM/U/URL.html');
        insert objCancelUWDOc;
        
        /*Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator()); 
        Test.stopTest();*/
          
        Account objAcc = new Account(Name='Test Acc');
        insert objAcc;
        
        contact objCon = new Contact(lastname='Test',Email='test@test.com',AccountId=objAcc.Id,Submission__c=true);
        insert objCon;
        
        Lead objLead = New Lead(LastName='Test1',Status='New',Company='TestCompany',Average_Monthly_Revenue__c='$10,000 - $24,999',Time_in_Business__c='1-3 Years',Phone='9632587410',country='Canada');
        insert objLead;
        
        Opportunity objOpp = new Opportunity(AccountId=objAcc.id,Opportunity_Owner_Manager__c=UserInfo.getUserId(),Name='Test Opp',StageName='App In Missing Info', CloseDate=system.today(),Lead__c=objLead.id, Cloufi__Dropbox_Folder_Path__c = 'test', Cancelled_Dropbox_Folder_Path__c = 'Test cancelled', Bank_statements_Email_to_Sales_Support__c = false);
        insert objOpp;
        
        Cloufi__Submission__c objSub = new Cloufi__Submission__c(Cloufi__Lender__c=objAcc.id,Cloufi__Opportunity__c=objOpp.id,Cloufi__Status__c='Requested');
        insert objSub;
        
        Cloufi__Offers__c objOffer = new Cloufi__Offers__c(Cloufi__Funder__c=objAcc.id,Cloufi__Opportunity__c=objOpp.id,Cloufi__Submission__c=objSub.id,Cloufi__Offer_Status__c='Approved');
        insert objOffer;
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new BitlyHttpCalloutMock());
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator()); 
            Cloufi__Application__c objApp = new Cloufi__Application__c(short_url__c='abc',cloufi__Opportunity__c =objOpp.id,Cloufi__Lead__c=objLead.id,Cloufi__Business_DBA_Name__c='TestCompany',Legal_Corporate_Name__c='TestCompany',Cloufi__Business_Legal_Name__c='Test',Cloufi__Industry_Type__c='Construction',Average_Monthly_Revenue__c='$250,000+',Time_in_Business__c='3-5 Years',Cloufi__First_Name__c='TestName',Cloufi__Last_Name__c='Test1',Cloufi__Email__c='test@gmail.com');
            insert objApp;
        Test.stopTest();

        
        
        Cloufi__UW_Document__c objUW = new Cloufi__UW_Document__c(Cloufi__URL__c='www.sfdc.com',Name='Test',Stip_Name__c='Signed Application',Cloufi__Opportunity__c=objOpp.Id,Cloufi__Application__c=objApp.id, Cloufi__Type__c='Application - Document', Status__c='Pending');
        insert objUW;
        objUW.Cloufi__URL__c = 'ww.salesforce.com';
        update objUW;
        
        Cloufi__UW_Document__c objBank ;
        List <Cloufi__UW_Document__c> uwList = new List <Cloufi__UW_Document__c>();
        for(Integer i=0; i<5; i++){
            objBank = new Cloufi__UW_Document__c();
            objBank.Cloufi__URL__c='www.sfdc.com';
            objBank.Name='Test';
            objBank.Stip_Name__c='February'+i+' Bank';
            objBank.Cloufi__Opportunity__c=objOpp.Id;
            objBank.Cloufi__Application__c=objApp.id;
            objBank.Cloufi__Type__c='Bank Statement';
            objBank.Status__c='Pending';
            uwList.add(objBank);
        }
        insert uwList;
        
        
        UW_Document_Share__c objShare = new UW_Document_Share__c(Account__c=objAcc.id,Opportunity__c=objOpp.id,UW_Documents__c=objUW.id);
        insert objShare;
    
        objOpp.stageName = 'Contract Requested';
        update objOpp;
    
        //delete objUW;
        Cloufi__UW_Document__c objUW2 = new Cloufi__UW_Document__c(Status__c = 'Requested',Cloufi__URL__c='https://www.sfdc.com',Name='Contract',Stip_Name__c='Contract',Cloufi__Opportunity__c=objOpp.Id,Cloufi__Application__c=objApp.id);
        insert objUW2;
        delete  objUW2;
        
        objOpp.stageName = 'Contract Sent';
        update objOpp;
        
        Cloufi__UW_Document__c objUW1 = new Cloufi__UW_Document__c(Status__c = 'Completed',Name='Test',Stip_Name__c='Signed Contract',Cloufi__Opportunity__c=objOpp.Id,Cloufi__Application__c=objApp.id);
        insert objUW1;
        UW_Document_Share__c objShare1 = new UW_Document_Share__c(Account__c=objAcc.id,Opportunity__c=objOpp.id,UW_Documents__c=objUW1.id);
        insert objShare1;
        
        
    }
}