objects/Chat__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Chats</relationshipLabel>
        <relationshipName>Chats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chat</label>
    <nameField>
        <displayFormat>MSG-{0000}</displayFormat>
        <label>Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesRepSupportController.cls
/*****************************************************************
* Author: Techila Global Services Pvt Ltd. (Aditya Mukkawar)
* Class Name: SalesRepSupportController (SalesRepSupportCompController_Test - Test class)
* Created Date: 21-September-2018
* Description: Controller for SalesRepSupport visulaforce component
*******************************************************************/
public class SalesRepSupportController{
    
    public Id oppId {get;set;}
    
    public string getOppLink(){
        if(oppId !=null){
            string base_URL = Label.Base_URL;
            return base_URL+'/'+oppId;
        }else{
            return null;
        }
        
    }
    
	//  To get Task which is assign to sales support
    public List<Chat__c> getMessageFormSalesRep(){
        if(oppId !=null){
            /*List<Task> taskListForSalesRep = new List<Task>();
            taskListForSalesRep = [SELECT id,whatId,Description,Subject FROM Task WHERE WhatId=:oppId and subject='Task Assign to Sales Support' Order by CreatedDate Desc LIMIT 1];
            if(taskListForSalesRep [0].Description !=null && taskListForSalesRep.size()>0){
                return taskListForSalesRep;
            }else{
                return null;
            }*/
            List<Chat__c> taskListForSalesRep = new List<Chat__c>();
            taskListForSalesRep = [SELECT id,Opportunity__c,Message__c,Subject__c FROM Chat__c WHERE Opportunity__c=:oppId and Subject__c='Task Assign to Sales Support' Order by CreatedDate Desc LIMIT 1];
            if(taskListForSalesRep [0].Message__c !=null && taskListForSalesRep.size()>0){
                return taskListForSalesRep;
            }else{
                return null;
            }
        }else{
            return null;
        }
    }
}