objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Submission__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submission</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Revenue__c</fullName>
        <label>Average Monthly Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>$0 - $4,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000 - $9,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$10,000 - $24,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25,000 - $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 - $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_in_Business__c</fullName>
        <label>Time in Business</label>
        <picklist>
            <picklistValues>
                <fullName>0-3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 months – 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-5 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5-10 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10+ Years</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Revenue__c</fullName>
        <label>Average Monthly Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>$0 - $4,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000 - $9,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$10,000 - $24,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25,000 - $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 - $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cloufi__Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Funder)</relationshipLabel>
        <relationshipName>Loans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_in_Business__c</fullName>
        <label>Time in Business</label>
        <picklist>
            <picklistValues>
                <fullName>10+ Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0-3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 months – 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-5 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5-10 Years</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UW_Document_Share__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UW Document Share</label>
    <nameField>
        <displayFormat>UW Share {0000}</displayFormat>
        <label>UW Document Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Document Share</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ChosenOfferComp_Ctl_Test.cls
@istest
public class ChosenOfferComp_Ctl_Test {
    
    public static testMethod void executeChosenOfferComp(){
        
        Account objAcc = new Account(Name='Test Account');
        insert objAcc;
        
        contact objCon = new Contact(lastname='Test',Email='test@test.com',AccountId=objAcc.Id,Submission__c=true);
        insert objCon;
	
        Lead objLead = New Lead(LastName='Test1',Status='New',Company='TestCompany',Average_Monthly_Revenue__c='$10,000 - $24,999',Time_in_Business__c='1-3 Years',Phone='9632587410',country='Canada');
        insert objLead;
        
        Opportunity objOpp = new Opportunity(AccountId=objAcc.id,Opportunity_Owner_Manager__c=UserInfo.getUserId(),Name='Test Opp',StageName='Contract Signed Partial', CloseDate=system.today(),Lead__c=objLead.id);
        insert objOpp;
        
        Cloufi__Submission__c objSub = new Cloufi__Submission__c(Cloufi__Lender__c=objAcc.id,Cloufi__Opportunity__c=objOpp.id,Cloufi__Status__c='Requested');
        insert objSub;
        
        Cloufi__Offers__c objOffer = new Cloufi__Offers__c(Cloufi__Funder__c=objAcc.id,Cloufi__Opportunity__c=objOpp.id,Cloufi__Submission__c=objSub.id,Cloufi__Offer_Status__c='Approved');
        insert objOffer;
        
        Cloufi__UW_Document__c objUw = new Cloufi__UW_Document__c(Cloufi__Opportunity__c=objOpp.Id,Stip_Name__c='Test Name',Cloufi__URL__c='www.salesforce.com');
        insert objUw;
        
        UW_Document_Share__c objShare = new UW_Document_Share__c(Account__c=objAcc.id,Opportunity__c=objOpp.id,UW_Documents__c=objUw.id);
        insert objShare;
        
        ChosenOfferComp_Ctl objCont = new ChosenOfferComp_Ctl();
        objCont.getOfferDocs();
        objCont.oppId = objOpp.id;
        objCont.getOfferDocs();
    }
    
}