objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Are_you_in_Bankruptcy_Consumer_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Are you in Bankruptcy/Consumer Proposal?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Revenue__c</fullName>
        <label>Average Monthly Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>$0 - $4,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000 - $9,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$10,000 - $24,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$25,000 - $49,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $99,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100,000 - $249,999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000+</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cloufi__Amount_Requested__c</fullName>
        <label>Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Business_DBA_Name__c</fullName>
        <label>Business DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Payment_Plan__c</fullName>
        <description>Will be controlled by field: &quot;Are you in Bankruptcy/Consumer Plan&quot;?</description>
        <label>Current Payment Plan</label>
        <picklist>
            <controllingField>Are_you_in_Bankruptcy_Consumer_Proposal__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interested_within_2_4_weeks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interested within 2-4 weeks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Application_Checklist_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Application Checklist Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Funding__c</fullName>
        <label>Purpose of Funding</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_in_Business__c</fullName>
        <label>Time in Business</label>
        <picklist>
            <picklistValues>
                <fullName>0-3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 months – 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-5 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5-10 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10+ Years</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_Of_Business__c</fullName>
        <label>Type Of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cooperative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Proprietorship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LeadTriggerHandler_Test.cls
@isTest
public class LeadTriggerHandler_Test {
    public static testmethod void executeLeadTriggerHandler(){
        Cloufi__Lead_Application_Field_Mapping__c objleadapplication = new Cloufi__Lead_Application_Field_Mapping__c(name = 'Last Name', Cloufi__Application_Field_API__c = 'Cloufi__Last_Name__c', Cloufi__Lead_Field_API__c = 'LastName');
        insert objleadapplication;
        
        Cloufi__Lead_Application_Field_Mapping__c objleadapplication1 = new Cloufi__Lead_Application_Field_Mapping__c(name = 'Company', Cloufi__Application_Field_API__c = 'Cloufi__Business_DBA_Name__c', Cloufi__Lead_Field_API__c = 'Company');
        insert objleadapplication1;
        
        Cloufi__Lead_Application_Field_Mapping__c objleadapplication2 = new Cloufi__Lead_Application_Field_Mapping__c(name = 'Lead', Cloufi__Application_Field_API__c = 'Cloufi__Lead__c', Cloufi__Lead_Field_API__c = 'Id');
        insert objleadapplication2;
        
        Lead objLead = New Lead(LastName='Test1',Status='New',Company='TestCompany',Average_Monthly_Revenue__c='$10,000 - $24,999',Time_in_Business__c='1-3 Years',Phone='9632587410',country='Canada');
        insert objLead;
    }
    
    public static testmethod void verifyAppChecklist(){
        
        
        Profile objProfile =[SELECT Id FROM Profile WHERE Name='Cash Advance Sales Agent OffShore'];
        User userRecord = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                        LocaleSidKey='en_US', ProfileId = objProfile.Id, 
                        TimeZoneSidKey='America/Los_Angeles', UserName='standarduser98745@testorg.com');
        insert userRecord;
        
        system.runAs(userRecord){
            Lead objLead = New Lead(LastName='Test1',Status='New',Company='TestCompany',Average_Monthly_Revenue__c='$10,000 - $24,999',Time_in_Business__c='1-3 Years',Phone='9632587410',country='Canada', Email='test@test.com');
            insert objLead;
            
            objLead.Type_Of_Business__c = 'Corporation';
            objLead.Are_you_in_Bankruptcy_Consumer_Proposal__c = true;
            objLead.Current_Payment_Plan__c = 'Yes';
            objLead.Interested_within_2_4_weeks__c = true;
            objLead.Cloufi__Business_DBA_Name__c = 'Test DBA';
            objLead.Time_in_Business__c = '4 months – 1 year';
            objLead.Average_Monthly_Revenue__c = '$10,000 - $24,999';
            objLead.Cloufi__Amount_Requested__c = 200;
            objLead.Purpose_of_Funding__c = 'Setup';
            
            objLead.Is_Application_Checklist_Completed__c = true;
            update objLead;
        }
    }
}