objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cloufi__Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Funder)</relationshipLabel>
        <relationshipName>Loans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UW_Document_Share__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UW Document Share</label>
    <nameField>
        <displayFormat>UW Share {0000}</displayFormat>
        <label>UW Document Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Document Share</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ChosenOfferComp_Ctl.cls
public class ChosenOfferComp_Ctl{
    
    public Id oppId {get;set;}
    
    public List<Cloufi__UW_Document__c> getOfferDocs(){
        if(oppId != null){
            Opportunity objopp = [SELECT id,AccountId,(SELECT id,Cloufi__Offer_Status__c,Cloufi__Funder__c FROM Cloufi__Offers__r WHERE Cloufi__Offer_Status__c='Approved' LIMIT 1) FROM Opportunity WHERE id=:oppId];
            
            List<UW_Document_Share__c> lstShareDocs = [SELECT id,UW_Documents__c,Account__c,UW_Documents__r.stip_name__c,UW_Documents__r.Cloufi__URL__c FROM UW_Document_Share__c WHERE Account__c=:objopp.Cloufi__Offers__r[0].Cloufi__Funder__c AND Opportunity__c=:oppId AND UW_Documents__r.Cloufi__URL__c!=null];
            set<Id> uwIds = new set<Id>();
            for(UW_Document_Share__c objShare:lstShareDocs){
                uwIds.add(objShare.UW_Documents__c);
            }
            List<Cloufi__UW_Document__c> lstUW = new List<Cloufi__UW_Document__c>();
            if(uwIds.size()>0){
                lstUW = [SELECT id,Stip_Name__c,Cloufi__URL__c FROM Cloufi__UW_Document__c WHERE id in:uwIds];
            }
            if(lstUW.size()>0){
                return lstUW;
            }else{
                return null;
            }
        }
        return null;
    }
}