objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cloufi__Dropbox_Folder_Path__c</fullName>
        <label>Dropbox Folder Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UW_Document_Share__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UW Document Share</label>
    <nameField>
        <displayFormat>UW Share {0000}</displayFormat>
        <label>UW Document Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Document Share</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DownloadUWDocCntl.cls
public with sharing class DownloadUWDocCntl {
    public Opportunity objOpportunity{get;set;}
    public List<String> filesPathList{get;set;}
    
    public DownloadUWDocCntl(ApexPages.StandardController controller) {
        String oppId = ApexPages.currentPage().getParameters().get('id');
        objOpportunity = new Opportunity();
        filesPathList = new List<String>();
        if(oppID != null){            
            objOpportunity = [SELECT ID,Name,Cloufi__Dropbox_Folder_Path__c FROM Opportunity WHERE ID =: oppID];            
            for(UW_Document_Share__c objDoc : [SELECT Id, Opportunity__r.Cloufi__Dropbox_Folder_Path__c, UW_Documents__c, UW_Documents__r.Cloufi__URL__c FROM UW_Document_Share__c WHERE UW_Documents__c != null AND UW_Documents__r.Cloufi__URL__c != null AND Opportunity__c =: oppId]){
                String filepath = '';
                filepath = objDoc.Opportunity__r.Cloufi__Dropbox_Folder_Path__c.trim();
                filepath += '/' + objDoc.UW_Documents__r.Cloufi__URL__c.substringAfterLast('/').substringBefore('?').replace('%20',' ');
                filesPathList.add(filePath);
            }
        }
    }
}