objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cloufi__Dropbox_Folder_Path__c</fullName>
        <label>Dropbox Folder Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UW_Document_Share__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UW_Documents__c</fullName>
        <label>UW Documents</label>
        <referenceTo>Cloufi__UW_Document__c</referenceTo>
        <relationshipLabel>UW Document Share</relationshipLabel>
        <relationshipName>UW_Document_Share</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UW Document Share</label>
    <nameField>
        <displayFormat>UW Share {0000}</displayFormat>
        <label>UW Document Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UW Document Share</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DownloadUWDocCntl_Test.cls
@isTest
public class DownloadUWDocCntl_Test 
{
    @isTest
    public static void testDownloadAllUWDocumentsControllerX()
    {
        // Fetch folder
        Folder lstFolder = [Select Id From Folder Where Name = 'Sales Tools'];
        
        //insert opportunity
        Opportunity objOpp = new Opportunity(); 
        objOpp.Name = 'Test Opp';
        objOpp.ForecastCategoryName = 'Pipeline';
        objOpp.CloseDate = System.today();
        objOpp.StageName = 'Qualified';
        objOpp.Cloufi__Dropbox_Folder_Path__c = lstFolder.Id;
        insert objOpp;
        
        // Insert UW Document'
        Cloufi__UW_Document__c objUW = new Cloufi__UW_Document__c(Cloufi__URL__c='www.sfdc.com',Name='Test',Stip_Name__c='Signed Application',Cloufi__Opportunity__c=objOpp.Id,Cloufi__Type__c='Bank Statement', Status__c='Pending');
        insert objUW;
        
        //Insert UW_Document_Share__c
        UW_Document_Share__c objUWDOC = new UW_Document_Share__c(UW_Documents__c = objUW.id, Opportunity__c = objOpp.id);
        insert objUWDOC;
        
        PageReference pageRef = Page.Download_UW_Documents;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(objOpp.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(objOpp);
        DownloadUWDocCntl objUWDocument = new DownloadUWDocCntl(sc);
    }
}