objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CloufiServicing__Submission_Country__c</fullName>
        <label>Submission Country</label>
        <picklist>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Puerto Rico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cloufi__Funder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funder</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (Funder)</relationshipLabel>
        <relationshipName>Loans3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloufi__Monthly_Revenue__c</fullName>
        <label>Monthly Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Type_of_Business__c</fullName>
        <label>Type of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurant/Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home-Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/updateOfferStatusBatch_test.cls
/*Author | Date       | Description
Neha     | 08/22/2018 | Test class for updateOfferStatusBatch
*/

@isTest
public class updateOfferStatusBatch_test {
    static testmethod void TestupdateOfferStatusBatch() {
        Account objAccount = new Account();
        objAccount.Name = 'Test Funder';
        insert objAccount;
        
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'test';
        oppObj.StageName = 'Application';
        oppobj.CloseDate = system.today();
        oppobj.isPrivate=true;
        oppobj.Cloufi__Monthly_Revenue__c = 10000;
        oppobj.Cloufi__Type_of_Business__c = 'test';
        oppobj.CloufiServicing__Submission_Country__c = 'United States';
        insert oppObj;
        
        Cloufi__Offers__c objOffer = new Cloufi__Offers__c();
        objOffer.Cloufi__Opportunity__c = oppObj.id;
        objOffer.Cloufi__Funder__c = objAccount.id;
        //objOffer.Cloufi__Submission__c = objSubmission.id;
        objOffer.Cloufi__Offer_Status__c = 'New';
        insert objOffer;
        
        Test.setCreatedDate(objOffer.Id, System.today()-31);

        
        Test.startTest();
        UpdateOfferStatusBatch objBatch = new UpdateOfferStatusBatch();
        Database.executeBatch(objBatch);
        Test.stopTest();
    }
}