objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CloufiServicing__Funding_Date__c</fullName>
        <label>Funding Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CloufiServicing__Payment_Installment__c</fullName>
        <label>Payment Installment</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Borrower_Email__c</fullName>
        <label>Borrower Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Cloufi__Daily_Payback_Amt__c</fullName>
        <label>Daily Payback Amt</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Factor_Rate__c</fullName>
        <label>Factor Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cloufi__Loan_Term__c</fullName>
        <label>Loan Term</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cloufi__Payback_Amount__c</fullName>
        <label>Payback Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cloufi__Percentage_Of_Gross__c</fullName>
        <label>Percentage Of Gross</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Payoff_Percentage_Time__c</fullName>
        <description>Used to show the Percentage of time to get the estimation of Payoff</description>
        <inlineHelpText>Used to show the Percentage of time to get the estimation of Payoff</inlineHelpText>
        <label>Payoff % (Time)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RenewalPayoffPercCalculationBatch_Test.cls
/**
Author | Date       | Description
Anuradha   | 04/29/2019 | Test class for RenewalPayoffPercentageCalculationBatch 
**/

@isTest(seeAllData = false)
public class RenewalPayoffPercCalculationBatch_Test {
    public static testmethod void renewalPayOffTest_1(){
        
        Account acc=new Account();
        acc.Name='Test';
        insert acc;
        system.assertNotequals(acc.id,null);
        
        Contact objContact = new Contact();
        objContact.LastName = 'Testing';
        objContact.Email = 'test@gmail.com';
        insert objContact;        
        
        Opportunity ObjLoan = new Opportunity();
        ObjLoan.Name = 'test';
        ObjLoan.CloufiServicing__Funding_Date__c = System.Today();
        ObjLoan.StageName = 'Funded';
        ObjLoan.amount = 100;
        ObjLoan.Cloufi__Payback_Amount__c= 100;   
        ObjLoan.Cloufi__Daily_Payback_Amt__c= 50;
        ObjLoan.Cloufi__Factor_Rate__c= 1.2;
        ObjLoan.Cloufi__Loan_Term__c= 12;        
        ObjLoan.Cloufi__Percentage_Of_Gross__c= 100;
        ObjLoan.Cloufi__Borrower_Email__c = 'test@gmail.com';
        ObjLoan.CloseDate =System.Today();
        ObjLoan.CloufiServicing__Payment_Installment__c = 75;
        ObjLoan.Payoff_Percentage_Time__c  = 1.0;
        insert ObjLoan;
        System.assertNotEquals(ObjLoan.id,null);
        
        Test.startTest();
        RenewalPayoffPercCalcSchedular sh1 = new RenewalPayoffPercCalcSchedular();
        String sch = '0 0 2 * * ?'; 
        system.schedule('Test Renewal PayOff Calc', sch, sh1); 
        Test.stopTest();
        
        
    }
}